[book]
title = "mesh-repair Documentation"
authors = ["mesh-repair contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/bigmark222/mesh"
edit-url-template = "https://github.com/bigmark222/mesh/edit/main/docs/{path}"
site-url = "/mesh/"
cname = ""
input-404 = "404.md"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = true
runnable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
